title = "Custom Gitleaks Config"

[allowlist]
description = "Ignore known false positives in README"
files = ["README.md"]
regexes = [
    '''cafebabe:deadbeef''',
    '''DB_PASSWORD=8ae31cacf141669ddfb5da'''
]
